import type { GeneratorContext, FormatterOptions, GeneratedFile } from "../types.js";
import {
  buildOverviewSection,
  buildConventionsSection,
  buildKeyComponentsSection,
  buildComponentTableSection,
  buildDependencySection,
  buildInsightsSection,
  buildGuidelinesSection,
  composeSectionsWithBudget,
} from "../sections.js";

export function formatClaude(
  context: GeneratorContext,
  options: FormatterOptions,
): readonly GeneratedFile[] {
  const name = options.projectName ?? "Project";

  const header = [
    `# ${name} — Architecture`,
    "",
    "Generated by [UIQuarter](https://github.com/niceguydave/uiquarter). Provides architectural context for AI-assisted development.",
  ].join("\n");

  const sections = [
    header,
    buildOverviewSection(context),
    buildConventionsSection(context.conventions),
    buildKeyComponentsSection(context),
    buildComponentTableSection(context),
    buildDependencySection(context),
    buildInsightsSection(context),
    buildGuidelinesSection(context),
  ].filter((s) => s.length > 0);

  const content = options.charBudget !== undefined
    ? composeSectionsWithBudget(sections, options.charBudget)
    : sections.join("\n\n");

  return [{ relativePath: "CLAUDE.md", content: content + "\n" }];
}
