import type { GeneratorContext, FormatterOptions, GeneratedFile } from "../types.js";
import {
  buildOverviewSection,
  buildConventionsSection,
  buildKeyComponentsSection,
  buildDependencySection,
  buildInsightsSection,
  buildGuidelinesSection,
  composeSectionsWithBudget,
} from "../sections.js";

const DEFAULT_CODEX_BUDGET = 32_768;

export function formatCodex(
  context: GeneratorContext,
  options: FormatterOptions,
): readonly GeneratedFile[] {
  const name = options.projectName ?? "Project";

  const header = [
    `# ${name} — Architecture`,
    "",
    "Generated by UIQuarter. Provides architectural context for AI-assisted development.",
  ].join("\n");

  const sections = [
    header,
    buildOverviewSection(context),
    buildConventionsSection(context.conventions),
    buildKeyComponentsSection(context),
    buildDependencySection(context),
    buildInsightsSection(context),
    buildGuidelinesSection(context),
  ].filter((s) => s.length > 0);

  const budget = options.charBudget ?? DEFAULT_CODEX_BUDGET;
  const content = composeSectionsWithBudget(sections, budget);

  return [{ relativePath: "AGENTS.md", content: content + "\n" }];
}
