import type { GeneratorContext, FormatterOptions, GeneratedFile } from "../types.js";
import {
  buildOverviewSection,
  buildConventionsSection,
  buildKeyComponentsSection,
  buildInstructionGuidelinesSection,
  composeSectionsWithBudget,
} from "../sections.js";

export function formatCopilot(
  context: GeneratorContext,
  options: FormatterOptions,
): readonly GeneratedFile[] {
  const name = options.projectName ?? "Project";

  const header = [
    `# ${name} — Project Context`,
    "",
    "Generated by UIQuarter.",
  ].join("\n");

  const sections = [
    header,
    buildOverviewSection(context),
    buildConventionsSection(context.conventions),
    buildKeyComponentsSection(context),
    buildInstructionGuidelinesSection(context),
  ].filter((s) => s.length > 0);

  const content = options.charBudget !== undefined
    ? composeSectionsWithBudget(sections, options.charBudget)
    : sections.join("\n\n");

  return [{ relativePath: ".github/copilot-instructions.md", content: content + "\n" }];
}
