import type { GeneratorContext, FormatterOptions, GeneratedFile } from "../types.js";
import {
  buildOverviewSection,
  buildConventionsSection,
  buildHubsOnlySection,
  buildDirectiveGuidelinesSection,
  composeSectionsWithBudget,
} from "../sections.js";

export function formatCursor(
  context: GeneratorContext,
  options: FormatterOptions,
): readonly GeneratedFile[] {
  const name = options.projectName ?? "Project";

  const header = [
    `# ${name} — Architecture`,
    "",
    "Generated by UIQuarter.",
  ].join("\n");

  const sections = [
    header,
    buildOverviewSection(context),
    buildConventionsSection(context.conventions),
    buildHubsOnlySection(context),
    buildDirectiveGuidelinesSection(context),
  ].filter((s) => s.length > 0);

  const content = options.charBudget !== undefined
    ? composeSectionsWithBudget(sections, options.charBudget)
    : sections.join("\n\n");

  return [{ relativePath: ".cursorrules", content: content + "\n" }];
}
