import type { GeneratorContext, FormatterOptions, GeneratedFile } from "../types.js";
import {
  buildCompactOverviewSection,
  buildCompactConventionsSection,
  buildHubsOnlySection,
  buildTopInsightsSection,
  composeSectionsWithBudget,
} from "../sections.js";

const DEFAULT_WINDSURF_BUDGET = 6_000;

export function formatWindsurf(
  context: GeneratorContext,
  options: FormatterOptions,
): readonly GeneratedFile[] {
  const name = options.projectName ?? "Project";

  const header = `# ${name}\n\nGenerated by UIQuarter.`;

  const sections = [
    header,
    buildCompactOverviewSection(context),
    buildCompactConventionsSection(context.conventions),
    buildHubsOnlySection(context),
    buildTopInsightsSection(context, 3),
  ].filter((s) => s.length > 0);

  const budget = options.charBudget ?? DEFAULT_WINDSURF_BUDGET;
  const content = composeSectionsWithBudget(sections, budget);

  return [{ relativePath: ".windsurfrules", content: content + "\n" }];
}
