import type { ProjectContext, ComponentContext } from "../context/ContextBuilder.js";
import { getReportCss, getReportJs } from "./template.js";

export interface ReportData {
  readonly project: ProjectContext;
  readonly generatedAt: string;
  readonly uxCoverage?: {
    readonly accessibility: number;
    readonly errorState: number;
    readonly loadingState: number;
    readonly responsive: number;
  };
}

// -----------------------------------------------------------------------------
// Public API
// -----------------------------------------------------------------------------

export function generateHtmlReport(data: ReportData): string {
  const css = getReportCss();
  const js = getReportJs();

  const summaryCards = renderSummaryCards(data);
  const depGraph = renderDependencyGraph(data);
  const componentTable = renderComponentTable(data);
  const insights = renderInsights(data);
  const uxCoverage = renderUxCoverage(data);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UIQuarter Report</title>
  <style>${css}</style>
</head>
<body>
  <div class="container">
    <h1>UIQuarter Report</h1>
    <p class="subtitle">Generated on ${escapeHtml(data.generatedAt)}</p>
    ${summaryCards}
    <h2>Dependency Graph</h2>
    ${depGraph}
    <h2>Components</h2>
    <input type="text" id="component-search" class="search" placeholder="Search components...">
    ${componentTable}
    <h2>Insights</h2>
    ${insights}
    ${uxCoverage}
    <footer>Generated by UIQuarter v0.1.0</footer>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>${js}</script>
</body>
</html>`;
}

// -----------------------------------------------------------------------------
// Internal renderers
// -----------------------------------------------------------------------------

function renderSummaryCards(data: ReportData): string {
  const { summary } = data.project;
  return `
    <div class="cards">
      <div class="card">
        <div class="value">${summary.totalComponents}</div>
        <div class="label">Components</div>
      </div>
      <div class="card">
        <div class="value">${summary.totalInsights}</div>
        <div class="label">Insights</div>
      </div>
      <div class="card">
        <div class="value">${summary.hubCount}</div>
        <div class="label">Hub Components</div>
      </div>
      <div class="card">
        <div class="value">${summary.deepChainCount}</div>
        <div class="label">Deep Chains</div>
      </div>
    </div>`;
}

function renderDependencyGraph(data: ReportData): string {
  const { components, hubs } = data.project;
  const hubNames = new Set(hubs.map((h) => h.component));

  // Select up to 30 nodes: hubs first, then by dependent count
  const hubComponents = components.filter((c) => hubNames.has(c.name));
  const nonHubComponents = components
    .filter((c) => !hubNames.has(c.name))
    .sort((a, b) => b.dependentCount - a.dependentCount);

  const selected: ComponentContext[] = [];
  const selectedNames = new Set<string>();

  for (const c of hubComponents) {
    if (selected.length >= 30) break;
    if (!selectedNames.has(c.name)) {
      selected.push(c);
      selectedNames.add(c.name);
    }
  }

  for (const c of nonHubComponents) {
    if (selected.length >= 30) break;
    if (!selectedNames.has(c.name)) {
      selected.push(c);
      selectedNames.add(c.name);
    }
  }

  if (selected.length === 0) {
    return `<div class="mermaid">graph TD\n  empty["No components found"]</div>`;
  }

  // Build mermaid graph
  const lines: string[] = ["graph TD"];
  lines.push("  classDef hub fill:#1f6feb,stroke:#58a6ff,color:#fff");

  // Add nodes
  for (const c of selected) {
    const safeId = sanitizeMermaidId(c.name);
    const label = escapeHtml(c.name);
    if (hubNames.has(c.name)) {
      lines.push(`  ${safeId}["${label}"]:::hub`);
    } else {
      lines.push(`  ${safeId}["${label}"]`);
    }
  }

  // Add edges: only between selected components
  // We infer edges from dependency counts by looking at the component list
  // Since we don't have explicit edge data in ProjectContext, we show
  // hub -> dependent relationships based on available data
  for (const c of selected) {
    if (c.dependencyCount > 0) {
      // Show connections to other selected components that are hubs
      for (const hub of hubComponents) {
        if (hub.name !== c.name && selectedNames.has(hub.name)) {
          const fromId = sanitizeMermaidId(c.name);
          const toId = sanitizeMermaidId(hub.name);
          lines.push(`  ${fromId} --> ${toId}`);
        }
      }
    }
  }

  const mermaidCode = lines.join("\n");
  return `<div class="mermaid">\n${mermaidCode}\n</div>`;
}

function renderComponentTable(data: ReportData): string {
  const { components } = data.project;

  if (components.length === 0) {
    return `<p>No components found.</p>`;
  }

  const rows = components.map((c) => {
    const tags: string[] = [];
    if (c.isHub) tags.push(`<span class="tag tag-hub">hub</span>`);
    if (c.isOrphan) tags.push(`<span class="tag tag-orphan">orphan</span>`);

    return `      <tr>
        <td>${escapeHtml(c.name)}</td>
        <td>${escapeHtml(c.filePath)}</td>
        <td>${c.dependencyCount}</td>
        <td>${c.dependentCount}</td>
        <td>${tags.join(" ")}</td>
      </tr>`;
  });

  return `
    <table id="component-table">
      <thead>
        <tr>
          <th data-sort="string">Name</th>
          <th data-sort="string">File</th>
          <th data-sort="number">Deps</th>
          <th data-sort="number">Dependents</th>
          <th>Tags</th>
        </tr>
      </thead>
      <tbody>
${rows.join("\n")}
      </tbody>
    </table>`;
}

function renderInsights(data: ReportData): string {
  const { insights } = data.project;

  if (insights.length === 0) {
    return `<p>No insights generated.</p>`;
  }

  // Group by severity: error first, then warning, then info
  const severityOrder: Record<string, number> = { error: 0, warning: 1, info: 2 };
  const sorted = [...insights].sort((a, b) => {
    const sa = severityOrder[a.severity] ?? 3;
    const sb = severityOrder[b.severity] ?? 3;
    return sa - sb;
  });

  const cards = sorted.map((insight) => {
    const severityClass = `severity-${insight.severity}`;
    const insightClass = `insight-${insight.severity}`;
    const componentLabel = insight.component
      ? ` <span style="color:#8b949e">in</span> ${escapeHtml(insight.component)}`
      : "";

    return `    <div class="insight ${insightClass}">
      <div class="title">
        <span class="severity ${severityClass}">${escapeHtml(insight.severity)}</span>
        ${escapeHtml(insight.type)}${componentLabel}
      </div>
      <div class="desc">${escapeHtml(insight.message ?? "")}</div>
    </div>`;
  });

  return cards.join("\n");
}

function renderUxCoverage(data: ReportData): string {
  if (!data.uxCoverage) {
    return "";
  }

  const metrics: Array<{ label: string; value: number }> = [
    { label: "Accessibility", value: data.uxCoverage.accessibility },
    { label: "Error States", value: data.uxCoverage.errorState },
    { label: "Loading States", value: data.uxCoverage.loadingState },
    { label: "Responsive", value: data.uxCoverage.responsive },
  ];

  const bars = metrics.map((m) => {
    const pct = Math.round(m.value * 100);
    const colorClass = pct >= 80 ? "coverage-good" : pct >= 50 ? "coverage-medium" : "coverage-low";
    return `    <div style="margin: 8px 0;">
      <div style="display: flex; justify-content: space-between; font-size: 13px;">
        <span>${escapeHtml(m.label)}</span>
        <span>${pct}%</span>
      </div>
      <div class="coverage-bar">
        <div class="coverage-fill ${colorClass}" style="width: ${pct}%"></div>
      </div>
    </div>`;
  });

  return `
    <h2>UX Coverage</h2>
    ${bars.join("\n")}`;
}

// -----------------------------------------------------------------------------
// Utilities
// -----------------------------------------------------------------------------

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function sanitizeMermaidId(name: string): string {
  // Mermaid node IDs must be alphanumeric (plus underscores)
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}
